### ISSUE TITLE
Limactl start not working, when `ed25519_sk` doesn't exist

### ISSUE THREAD

**Issue by max-wittig** [lima-vm/lima#198] opened 2021-09-03 09:42 UTC
Try to start lima on a new machine

## How to reproduce

Make sure that your `~/.ssh` looks like this: <img width="512" alt="image" src="https://user-images.githubusercontent.com/6639323/131984739-544d3ab4-581a-4566-b28b-c3f2cb0ea433.png">

---

1. Install lima with brew:  `brew install lima`
2. Run `limactl start`
3. Use the default configuration
4. Notice the crash, because `ed25519_sk` doesn't exist
> ? Creating an instance "default" Proceed with the default configuration
INFO[0005] Downloading "https://github.com/containerd/nerdctl/releases/download/v0.11.1/nerdctl-full-0.11.1-linux-amd64.tar.gz" (sha256:ce7a6e119b03c3fb8ded3d46d929962fd17417bea1d5bbc07e0fce49494d8a09) 
172.67 MiB / 172.67 MiB [----------------------------------] 100.00% 30.20 MiB/s
INFO[0012] Downloaded "nerdctl-full-0.11.1-linux-amd64.tar.gz" 
INFO[0014] Attempting to download the image from "~/Downloads/hirsute-server-cloudimg-amd64.img" 
INFO[0014] Attempting to download the image from "https://cloud-images.ubuntu.com/hirsute/current/hirsute-server-cloudimg-amd64.img" 
554.25 MiB / 554.25 MiB [----------------------------------] 100.00% 10.14 MiB/s
INFO[0071] Downloaded image from "https://cloud-images.ubuntu.com/hirsute/current/hirsute-server-cloudimg-amd64.img" 
INFO[0073] [hostagent] time="2021-09-03T11:24:45+02:00" level=fatal msg="stat /Users/max/.ssh/ed25519_sk: no such file or directory" 
FATA[0073] host agent process has exited: exit status 1

## Workaround

Create empty `ed25519_sk` file: 

```sh
touch ~/.ssh/ed25519_sk
```

**Comment by AkihiroSuda** [comment] 2021-09-03 10:14
Thanks for reporting.

Seems duplicate of #182, fixed in https://github.com/lima-vm/lima/pull/184.

The fix will be included in v0.6.2 (perhaps next week)

**Closed by AkihiroSuda** 2021-09-03 10:14 UTC
