### ISSUE TITLE
Any plans on supporting nixOS?

### ISSUE THREAD

**Issue by HknLof** [lima-vm/lima#1010] opened 2022-08-05 16:52 UTC
### Description

Hi Team, with the following configuration:
```
images:
- location: "https://channels.nixos.org/nixos-22.05/latest-nixos-minimal-x86_64-linux.iso"
  arch: "x86_64"
  digest: "sha256:a7fcc90948740b0a39fc0c657d24c59ddd7b1deb521fd3bff39a82b06596643e"
mounts:
- location: "~"
- location: "/tmp/lima"
  writable: true
firmware:
  legacyBIOS: true
```

The iso gets downloaded and booted, but hangs waiting for ssh:

```
? Creating an instance "nixos" Proceed with the current configuration
INFO[0001] Attempting to download the image from "https://channels.nixos.org/nixos-22.05/latest-nixos-minimal-x86_64-linux.iso"  digest="sha256:a7fcc90948740b0a39fc0c657d24c59ddd7b1deb521fd3bff39a82b06596643e"
820.00 MiB / 820.00 MiB [----------------------------------] 100.00% 12.15 MiB/s
INFO[0069] Downloaded the image from "https://channels.nixos.org/nixos-22.05/latest-nixos-minimal-x86_64-linux.iso"
INFO[0070] Attempting to download the nerdctl archive from "https://github.com/containerd/nerdctl/releases/download/v0.21.0/nerdctl-full-0.21.0-linux-amd64.tar.gz"  digest="sha256:728f9b543374b1b1733f759608e156dbe578d7b140a081084a1f4bfb4f2b3fbf"
217.85 MiB / 217.85 MiB [----------------------------------] 100.00% 10.16 MiB/s
INFO[0092] Downloaded the nerdctl archive from "https://github.com/containerd/nerdctl/releases/download/v0.21.0/nerdctl-full-0.21.0-linux-amd64.tar.gz"
INFO[0094] [hostagent] Starting QEMU (hint: to watch the boot progress, see "/Users/home/.lima/nixos/serial.log")
INFO[0094] SSH Local Port: 55060
INFO[0094] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0136] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0146] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0156] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0167] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0177] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0187] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0197] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0207] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0217] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0228] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0238] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0248] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0258] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
```

**Comment by AkihiroSuda** [comment] 2022-08-07 15:20
Duplicate of

- https://github.com/lima-vm/lima/discussions/430

**Closed by AkihiroSuda** 2022-08-07 15:20 UTC
