### ISSUE TITLE
nerdctl use older version after download new one

### ISSUE THREAD

**Issue by icyleaf** [lima-vm/lima#652] opened 2022-02-16 09:04 UTC
### Description

```
❯ limactl start
INFO[0000] Using the existing instance "default"
INFO[0000] Attempting to download the nerdctl archive from "https://github.com/containerd/nerdctl/releases/download/v0.17.0/nerdctl-full-0.17.0-linux-amd64.tar.gz"  digest=
201.43 MiB / 201.43 MiB [-----------------------------------] 100.00% 3.69 MiB/s
INFO[0057] Downloaded the nerdctl archive from "https://github.com/containerd/nerdctl/releases/download/v0.17.0/nerdctl-full-0.17.0-linux-amd64.tar.gz"
INFO[0057] [hostagent] Replacing "http_proxy" value "http://127.0.0.1:7890" with "http://192.168.5.2:7890"
INFO[0058] [hostagent] Replacing "https_proxy" value "http://127.0.0.1:7890" with "http://192.168.5.2:7890"
INFO[0063] [hostagent] Starting QEMU (hint: to watch the boot progress, see "/Users/icyleaf/.lima/default/serial.log")
INFO[0064] SSH Local Port: 60022
INFO[0064] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0092] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
INFO[0093] [hostagent] The essential requirement 1 of 5 is satisfied
INFO[0093] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh"
INFO[0093] [hostagent] The essential requirement 2 of 5 is satisfied
INFO[0094] [hostagent] Waiting for the essential requirement 3 of 5: "sshfs binary to be installed"
INFO[0094] [hostagent] The essential requirement 3 of 5 is satisfied
INFO[0094] [hostagent] Waiting for the essential requirement 4 of 5: "/etc/fuse.conf to contain \"user_allow_other\""
INFO[0094] [hostagent] The essential requirement 4 of 5 is satisfied
INFO[0094] [hostagent] Waiting for the essential requirement 5 of 5: "the guest agent to be running"
INFO[0094] [hostagent] The essential requirement 5 of 5 is satisfied
INFO[0094] [hostagent] Mounting "/Users/icyleaf"
INFO[0094] [hostagent] Mounting "/tmp/lima"
INFO[0094] [hostagent] Waiting for the optional requirement 1 of 2: "systemd must be available"
INFO[0094] [hostagent] Forwarding "/run/lima-guestagent.sock" (guest) to "/Users/icyleaf/.lima/default/ga.sock" (host)
INFO[0095] [hostagent] The optional requirement 1 of 2 is satisfied
INFO[0095] [hostagent] Waiting for the optional requirement 2 of 2: "containerd binaries to be installed"
INFO[0095] [hostagent] Not forwarding TCP 127.0.0.53:53
INFO[0095] [hostagent] Not forwarding TCP 0.0.0.0:22
INFO[0095] [hostagent] Not forwarding TCP [::]:22
INFO[0095] [hostagent] The optional requirement 2 of 2 is satisfied
INFO[0095] [hostagent] Waiting for the final requirement 1 of 1: "boot scripts must have finished"
INFO[0095] [hostagent] The final requirement 1 of 1 is satisfied
INFO[0095] READY. Run `lima` to open the shell.

❯ lima
$ nerdctl -v
nerdctl version 0.16.1
```

# Result

- expect version: 0.17.0
- got version: 0.16.1

# Sources

- limactl detect new version
- configure the location of nerdctl 

# Workaround

Delete the `/usr/local/bin/nerdctl` (because of [this](https://github.com/lima-vm/lima/blob/7656fa1/pkg/cidata/cidata.TEMPLATE.d/boot/40-install-containerd.sh#L11-L17)) and restart it, it will reinstall  the `nerdctl-full.xxx.tar.gz`.

**Comment by scbizu** [comment] 2022-02-16 11:37
https://github.com/lima-vm/lima/blob/v0.8.2/pkg/limayaml/defaults.go#L24 

lima v0.8.2(the latest) still uses the nerdctl v0.16.1 , you overrided the containerd archive ? 

BTW , for this kind of beta user , I think `sudo rm /usr/local/bin/nerdctl` with `lima shell`  and restart lima default instance is enough .

**Comment by AkihiroSuda** [comment] 2022-02-16 11:44
Duplicate of https://github.com/lima-vm/lima/issues/303

> When will lima cut the new release to support nerdctl v0.17.0 ?

In a few days

**Closed by AkihiroSuda** 2022-02-16 11:44 UTC

**Comment by icyleaf** [comment] 2022-02-17 00:05
> https://github.com/lima-vm/lima/blob/v0.8.2/pkg/limayaml/defaults.go#L24 
> 
> 
> 
> lima v0.8.2(the latest) still uses the nerdctl v0.16.1 , you overrided the containerd archive ? 
> 
> 
> 
> BTW , for this kind of beta user , I think `sudo rm /usr/local/bin/nerdctl` with `lima shell`  and restart lima default instance is enough .

Firstly, if this solution can be documented it should help more people, secondly, I upgraded from using the lima version of nerdctl 0.16.0 to using the latest version of netdctl 0.16.1 and it did not replace it, from the latter it is a bug that needs to be fixed.
