### ISSUE TITLE
brew Error: lima: SHA256 mismatch

### ISSUE THREAD

**Issue by Jasstkn** [lima-vm/lima#500] opened 2021-12-28 07:40 UTC
Hi.
During the lima installation on M1 MacBook, I faced with the following issue:
```
==> Downloading https://git.savannah.gnu.org/cgit/guile.git/patch/?id=1f100a4f20c3a6e57922fb26fce212997e2a03cb
Already downloaded: /Users/mariarti/Library/Caches/Homebrew/downloads/ed0ab6d9aa9892d417f166b6aca3db95c5c2eab4a4e3c6f5a74a585c956debf6--9a62f7cacaf730fca07f6cfd400a1893c2c2acb6..1f100a4f20c3a6e57922fb26fce212997e2a03cb.patch
Error: lima: SHA256 mismatch
Expected: a5adf2586b30381cf24524c7fc0364115f7cb1f568d2b69a9f3fb49ad8355b55
  Actual: a857c5fde2eb1c05379a97ba88047404da1c5b1da0291903f036d0a8745d85b5
    File: /Users/mariarti/Library/Caches/Homebrew/downloads/ed0ab6d9aa9892d417f166b6aca3db95c5c2eab4a4e3c6f5a74a585c956debf6--9a62f7cacaf730fca07f6cfd400a1893c2c2acb6..1f100a4f20c3a6e57922fb26fce212997e2a03cb.patch
To retry an incomplete download, remove the file above.
``` 

I've tried to apply solutions for similar problems with other packages but no luck so far.

**Comment by AkihiroSuda** [comment] 2021-12-28 07:55
> ==> Downloading https://git.savannah.gnu.org/cgit/guile.git/patch/?id=1f100a4f20c3a6e57922fb26fce212997e2a03cb

Doesn't seem related to Lima, and duplicate of:
- https://github.com/Homebrew/homebrew-core/issues/92080
- https://github.com/Homebrew/homebrew-core/issues/92086

**Closed by AkihiroSuda** 2021-12-28 07:55 UTC

**Comment by Jasstkn** [comment] 2021-12-28 14:27
@AkihiroSuda that's correct. Thank you.
