### ISSUE TITLE
Cannot Create OpenSUSE Tumbleweed Instance

### ISSUE THREAD

**Issue by 8bitZeta** [lima-vm/lima#2409] opened 2024-06-09 18:31 UTC
### Description

Any time I use the existing template for OpenSUSE Tumbleweed, I get stuck in a loop of "user session is ready for ssh". 

No idea if this is known or not, but I figured I should submit an issue for it.

**Comment by AkihiroSuda** [comment] 2024-06-09 22:34
Probably a duplicate of:
- https://github.com/lima-vm/lima/issues/1496

**Comment by afbjorklund** [comment] 2024-06-10 07:21
The ssh works, but not `/run/lima-ssh-ready`

```
/var/log/cloud-init-output.log:LIMA 2024-06-10T09:15:55+02:00| Executing /mnt/lima-cidata/boot/07-etc-environment.sh
/var/log/cloud-init-output.log-++ test -f /etc/environment
/var/log/cloud-init-output.log-+ orig=
/var/log/cloud-init-output.log:LIMA 2024-06-10T09:15:55+02:00| WARNING: Failed to execute /mnt/lima-cidata/boot/07-etc-environment.sh
```

**Comment by afbjorklund** [comment] 2024-06-10 07:28
The error needs to be handled, somehow.

```sh
orig=$(test -f /etc/environment && cat /etc/environment || true)
```

**Closed** 2024-06-11 00:19 UTC
Labels: guest/opensuse
