### ISSUE TITLE
Support nested virtualization

### ISSUE THREAD

**Issue by kopiczko** [lima-vm/lima#477] opened 2021-12-13 18:26 UTC
I'd like to ask if there is a chance to have nested virtualization? I tried steps from https://docs.fedoraproject.org/en-US/quick-docs/using-nested-virtualization-in-kvm/ but TBH I have no idea what I'm doing. I need kvm in particular to be able to [build capi images](https://image-builder.sigs.k8s.io/capi/providers/openstack.html).

**Comment by afbjorklund** [comment] 2021-12-13 18:48
It should be doable, but might need some special flags:

```console
anders@lima-default:/home/anders$ kvm-ok 
INFO: /dev/kvm exists
KVM acceleration can be used
```

**Comment by kopiczko** [comment] 2021-12-13 21:04
I'm on macOS Monterey and with default ubuntu `/dev/kvm` doesn't exist. It's the same with fedora 35.

**Comment by afbjorklund** [comment] 2021-12-13 21:22
Sorry, I thought you were on real Ubuntu. So you want three levels of Inception, when it hits the water ?

**Comment by afbjorklund** [comment] 2021-12-13 21:24
I think the commercial options (VMware and Parallels) do it, but I don't think QEMU supports it (on Mac)

**Comment by jandubois** [comment] 2021-12-13 21:28
I'm not sure, but I don't think qemu supports nested virtualization like that on macOS. 

I know it works with VMware Fusion, but it is a commercial product. I.e. you can run Ubuntu on Fusion, and then run Lima inside the Ubuntu VM (you need to enable nested virtualization, and possibly virtualized performance counters).

**Comment by afbjorklund** [comment] 2021-12-13 21:30
I didn't understand where Lima entered the picture, instead of running the image builder with HVF instead of KVM ?

**Comment by AkihiroSuda** [comment] 2021-12-14 04:16
Duplicate of https://github.com/lima-vm/lima/issues/22

**Closed by AkihiroSuda** 2021-12-14 04:16 UTC
Labels: duplicate
