### ISSUE TITLE
[Ubuntu on M1] Lima VM will not start (`EFI stub: ERROR: FIRMWARE BUG: kernel image not aligned on 64k boundary`)

### ISSUE THREAD

**Issue by mateka** [lima-vm/lima#712] opened 2022-03-10 11:07 UTC
# EDIT by @AkihiroSuda 

## Update (Mar 14, 2022)
:warning: Running recent Linux guests on M1 macOS needs Homebrew's QEMU 6.2.0_1 or later.

**Run `brew upgrade` to upgrade QEMU.**

Intel macOS users are NOT affected by this issue.

For the further information, see https://github.com/lima-vm/lima/pull/734 and https://github.com/Homebrew/homebrew-core/pull/96743 .

<details>
<summary>Old information</summary>
<p>

Ubuntu kernel 5.13.0-35.40 (5.4.0-103.117 for 20.04 LTS) released in March 2022 is not bootable on ARM hosts:
```
(~/.lima/default/serial.log)
...
EFI stub: Booting Linux Kernel...
EFI stub: ERROR: FIRMWARE BUG: kernel image not aligned on 64k boundary
EFI stub: Using DTB from configuration table
EFI stub: Exiting boot services and installing virtual address map...
SetUefiImageMemoryAttributes - 0x000000013F500000 - 0x0000000000040000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000013C190000 - 0x0000000000040000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000013C140000 - 0x0000000000040000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000013F4C0000 - 0x0000000000030000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000013C0F0000 - 0x0000000000040000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000013BCB0000 - 0x0000000000040000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000013BB00000 - 0x0000000000030000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000013BAC0000 - 0x0000000000030000 (0x0000000000000008)
(hangs here)
```

Until the issue gets resolved, it is HIGHLY RECOMMENDED to run the following command inside the Ubuntu shell to avoid upgrading the kernel:

```shell
sudo apt-mark hold linux-image-$(uname -r)
```
(Make sure to unhold it when we get the fix)

If your kernel was already upgraded and the VM does not boot, try running Lima with the following environment variable to show the video display:
```shell
export QEMU_SYSTEM_AARCH64="qemu-system-aarch64 -display cocoa"
```

After the display is shown, press the Esc key several times to show the GRUB prompt for choosing an older kernel.
You can also mount the disk image from another instance to modify the GRUB config or rescue the data inside the image.
https://github.com/lima-vm/lima/issues/712#issuecomment-1065266828

See also https://gitlab.com/qemu-project/qemu/-/issues/899

## :pray: Help wanted for testing

This QEMU patch may fix the issue: https://github.com/AkihiroSuda/homebrew-core/commit/177d583c741f4f50a12f326f632c54dbf169d37b
(from https://gitlab.com/qemu-project/qemu/-/issues/899)

Download `qemu.rb` and run `brew install --build-from-source ./qemu.rb` to apply the patch.

</p>
</details>

# Below is the original post by @mateka
- - -
### Description

Today I was working in lima VM (Ubuntu 20.04; Mac M1). After a while, it has lost connection (as it often does), so I had tried to restart it. Old VM and even brand new will not start and return an error after:

> Waiting for the essential requirement 1 of 5: "ssh"

`limactl --debug start VM-name` prints:

> DEBU[0171] [hostagent] executing ssh for script "ssh": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile="/Users/matek/.lima/_config/user" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers="^aes128-gcm@openssh.com,aes256-gcm@openssh.com" -o User=matek -o ControlMaster=auto -o ControlPath="/Users/matek/.lima/test/ssh.sock" -o ControlPersist=5m -p 52070 127.0.0.1 -- /bin/bash] 
> DEBU[0246] [hostagent] stdout="", stderr="kex_exchange_identification: read: Connection reset by peer\r\nConnection reset by 127.0.0.1 port 52070\r\n", err=failed to execute script "ssh": stdout="", stderr="kex_exchange_identification: read: Connection reset by peer\r\nConnection reset by 127.0.0.1 port 52070\r\n": exit status 255 

Rancher Desktop seems to work.

**Comment by AkihiroSuda** [comment] 2022-03-10 11:15
Do you see any error in ~/.lima/test/serial.log ?

**Comment by mateka** [comment] 2022-03-10 11:17
I am only seeing is:

> EFI stub: ERROR: FIRMWARE BUG: kernel image not aligned on 64k boundary

Here is full log:

[serial.log](https://github.com/lima-vm/lima/files/8222873/serial.log)

**Comment by AkihiroSuda** [comment] 2022-03-10 11:20
Could you provide Lima version, QEMU version, and `/Users/matek/.lima/test/lima.yaml` ?

**Comment by mateka** [comment] 2022-03-10 11:23
Both are installed from brew:
```
> limactl -v                                                                                                                                                                                                
limactl version 0.8.3
> qemu-system-aarch64 --version
QEMU emulator version 6.2.0
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers
```

[lima.yaml.txt](https://github.com/lima-vm/lima/files/8222912/lima.yaml.txt)

**Comment by AkihiroSuda** [comment] 2022-03-10 11:26
Thanks
- Does this work?  `limactl rm -f test && limactl prune && limactl start`
- Does Fedora image work? https://github.com/lima-vm/lima/blob/v0.8.3/examples/fedora.yaml

**Comment by mateka** [comment] 2022-03-10 11:46
For the clear Ubuntu test, I have used default settings. Still, it is not working:
```
limactl rm -f test && limactl prune && limactl start
INFO[0000] The QEMU process seems already stopped       
INFO[0000] The host agent process seems already stopped 
INFO[0000] Removing *.pid *.sock under "/Users/matek/.lima/test" 
INFO[0000] Deleted "test" ("/Users/matek/.lima/test")   
INFO[0000] Pruning "/Users/matek/Library/Caches/lima"   
? Creating an instance "default" Proceed with the default configuration
INFO[0001] Attempting to download the image from "~/Downloads/impish-server-cloudimg-arm64.img"  digest=
INFO[0001] Attempting to download the image from "https://cloud-images.ubuntu.com/impish/current/impish-server-cloudimg-arm64.img"  digest=
539.62 MiB / 539.62 MiB [----------------------------------] 100.00% 40.59 MiB/s
INFO[0016] Downloaded image from "https://cloud-images.ubuntu.com/impish/current/impish-server-cloudimg-arm64.img" 
INFO[0016] Attempting to download the nerdctl archive from "https://github.com/containerd/nerdctl/releases/download/v0.17.0/nerdctl-full-0.17.0-linux-arm64.tar.gz"  digest="sha256:b0ae2fc89d362afa18afcc35798d4da613096613d06cae07181b777cd66002e8"
173.82 MiB / 173.82 MiB [----------------------------------] 100.00% 29.51 MiB/s
INFO[0023] Downloaded the nerdctl archive from "https://github.com/containerd/nerdctl/releases/download/v0.17.0/nerdctl-full-0.17.0-linux-arm64.tar.gz" 
INFO[0024] [hostagent] Starting QEMU (hint: to watch the boot progress, see "/Users/matek/.lima/default/serial.log") 
INFO[0024] SSH Local Port: 60022                        
INFO[0024] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0110] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0195] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0280] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0365] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0450] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0536] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0621] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
FATA[0623] did not receive an event with the "running" status 
```
[serial.log](https://github.com/lima-vm/lima/files/8223016/serial.log)

Fedora seems working:
```
❯ limactl start
? Creating an instance "default" Open an editor to override the configuration
INFO[0039] Attempting to download the image from "https://download.fedoraproject.org/pub/fedora/linux/releases/35/Cloud/aarch64/images/Fedora-Cloud-Base-35-1.2.aarch64.qcow2"  digest="sha256:c71f2e6ce75b516d565e2c297ea9994c69b946cb3eaa0a4bbea400dbd6f59ae6"
359.94 MiB / 359.94 MiB [----------------------------------] 100.00% 23.11 MiB/s
INFO[0057] Downloaded image from "https://download.fedoraproject.org/pub/fedora/linux/releases/35/Cloud/aarch64/images/Fedora-Cloud-Base-35-1.2.aarch64.qcow2" 
INFO[0057] Attempting to download the nerdctl archive from "https://github.com/containerd/nerdctl/releases/download/v0.17.0/nerdctl-full-0.17.0-linux-arm64.tar.gz"  digest="sha256:b0ae2fc89d362afa18afcc35798d4da613096613d06cae07181b777cd66002e8"
173.82 MiB / 173.82 MiB [----------------------------------] 100.00% 27.12 MiB/s
INFO[0064] Downloaded the nerdctl archive from "https://github.com/containerd/nerdctl/releases/download/v0.17.0/nerdctl-full-0.17.0-linux-arm64.tar.gz" 
INFO[0065] [hostagent] Starting QEMU (hint: to watch the boot progress, see "/Users/matek/.lima/default/serial.log") 
INFO[0065] SSH Local Port: 60022                        
INFO[0065] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0085] [hostagent] The essential requirement 1 of 5 is satisfied 
INFO[0085] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh" 
INFO[0085] [hostagent] The essential requirement 2 of 5 is satisfied 
INFO[0085] [hostagent] Waiting for the essential requirement 3 of 5: "sshfs binary to be installed" 
INFO[0106] [hostagent] The essential requirement 3 of 5 is satisfied 
INFO[0106] [hostagent] Waiting for the essential requirement 4 of 5: "/etc/fuse.conf to contain \"user_allow_other\"" 
INFO[0110] [hostagent] The essential requirement 4 of 5 is satisfied 
INFO[0110] [hostagent] Waiting for the essential requirement 5 of 5: "the guest agent to be running" 
INFO[0110] [hostagent] The essential requirement 5 of 5 is satisfied 
INFO[0110] [hostagent] Mounting "/Users/matek"          
INFO[0110] [hostagent] Mounting "/tmp/lima"             
INFO[0110] [hostagent] Forwarding "/run/lima-guestagent.sock" (guest) to "/Users/matek/.lima/default/ga.sock" (host) 
INFO[0110] [hostagent] Waiting for the optional requirement 1 of 2: "systemd must be available" 
INFO[0110] [hostagent] Forwarding TCP from 0.0.0.0:5355 to 127.0.0.1:5355 
INFO[0110] [hostagent] The optional requirement 1 of 2 is satisfied 
INFO[0110] [hostagent] Waiting for the optional requirement 2 of 2: "containerd binaries to be installed" 
INFO[0110] [hostagent] Not forwarding TCP 127.0.0.53:53 
INFO[0110] [hostagent] Not forwarding TCP 0.0.0.0:22    
INFO[0110] [hostagent] Forwarding TCP from [::]:5355 to 127.0.0.1:5355 
WARN[0110] [hostagent] failed to set up forwarding tcp port 5355 (negligible if already forwarded) 
INFO[0110] [hostagent] Not forwarding TCP [::]:22       
INFO[0110] [hostagent] The optional requirement 2 of 2 is satisfied 
INFO[0110] [hostagent] Waiting for the final requirement 1 of 1: "boot scripts must have finished" 
INFO[0126] [hostagent] The final requirement 1 of 1 is satisfied 
INFO[0126] READY. Run `lima` to open the shell. 
```
[serial.log](https://github.com/lima-vm/lima/files/8223047/serial.log)

**Comment by AkihiroSuda** [comment] 2022-03-10 11:56
This might be a regression in https://cloud-images.ubuntu.com/impish/20220309/ ?

Does https://cloud-images.ubuntu.com/impish/20220201/ work?

**Comment by mateka** [comment] 2022-03-10 12:05
Here is [lima.yaml.txt](https://github.com/lima-vm/lima/files/8223176/lima.yaml.txt) with https://cloud-images.ubuntu.com/impish/20220201/. It is working!

**Comment by huysal** [comment] 2022-03-10 16:59
I have the same error as mateka but `limactl prune` doesn't seem to delete the stored image. I changed the image url und when I execute `limactl start docker` it does not download the image but end with the same error.

`limactl version 0.8.3`
`QEMU emulator version 6.2.0`

My `~/Library/Caches` has no `lima` folder. Any ideas? My `serial.log` looks pretty much the same as matekas.

Thanks in advance

**Comment by fuzmish** [comment] 2022-03-10 18:32
I'm facing exactly the same issue, and fixed by using `impish/20220201` image (as @mateka mentioned above).
It might be better to specify some stable release for `images.location` instead of the settings that changes its actual content unexpectedly such as `impish/current`.

@huysal Maybe we should remove (`limactl rm ...`) the VM and create a new one. I did that and it worked for me.

**Comment by AkihiroSuda** [comment] 2022-03-11 03:50
@mateka @huysal @fuzmish Thank you for testing and analysis. Obviously, this is a regression on Ubuntu side.
I'll update the YAML to use the Feb revision of image, but probably `apt-get upgrade` is still affected 😞 

@fuzmish Could you report this to Ubuntu? https://bugs.launchpad.net/ubuntu/+source/grub2/+bug/1947046

**Comment by AkihiroSuda** [comment] 2022-03-11 08:09
Released v0.9.0: https://github.com/lima-vm/lima/releases/tag/v0.9.0

This release uses https://cloud-images.ubuntu.com/releases/21.10/release-20220201 by default, and print a warning message to recommend `sudo apt-mark hold linux-image-$(uname -r)`.

**Comment by mateka** [comment] 2022-03-11 08:11
Is there a way to reuse VM broken by `apt-get upgrade`?

**Comment by AkihiroSuda** [comment] 2022-03-11 08:12
> Is there a way to reuse VM broken by `apt-get upgrade`?

`export QEMU_SYSTEM_AARCH64="qemu-system-aarch64 -display cocoa"`, and you can enter the GRUB prompt to choose an older kernel

**Comment by mateka** [comment] 2022-03-11 08:17
Great! Now it shows a login prompt. Is there a default login?

**Comment by AkihiroSuda** [comment] 2022-03-11 08:19
> Great! Now it shows a login prompt. Is there a default login?

No, please use `limactl shell`.
You can also use `limactl show-ssh` to show the underlying SSH command flags.

**Comment by mateka** [comment] 2022-03-11 08:20
Ok. Now it works! Thank You very much!

**Comment by adonishong** [comment] 2022-03-11 16:18
I'm facing exactly the same issue, there are some important projects files in this VM, and no backup anywhere else, so I could not rm this VM. And with output qemu display to cocoa and try to enter GRUB way, I am also failed. Keeping press ESC will lead me into UEFI menu. After I press continue inside UEFI menu, and then keeping press ESC, I could not enter GRUB menu ... Just get 4 EFI related information, including "EFI stub: ERROR: FIRMWARE BUG: kernel image not alligned on 64k boundary", and stuck there ...

Did I do anything wrong in enterring GRUB menu?

**Comment by mateka** [comment] 2022-03-11 20:02
I have restarted VM multiple times before configuring GRUB. Once it was stuck and was not accepting Esc. Other times it has not needed Esc to go into the GRUB menu.

**Comment by AkihiroSuda** [comment] 2022-03-12 04:24
Can anybody confirm that this patch works with https://cloud-images.ubuntu.com/releases/21.10/release-20220309/ ?

https://github.com/AkihiroSuda/homebrew-core/commit/177d583c741f4f50a12f326f632c54dbf169d37b

(Download `qemu.rb` and run `brew install --build-from-source ./qemu.rb`)

**Comment by fuzmish** [comment] 2022-03-12 06:53
@AkihiroSuda I have tested several Ubuntu image-based VMs with patched QEMU installed with [qemu.rb](https://raw.githubusercontent.com/AkihiroSuda/homebrew-core/177d583c741f4f50a12f326f632c54dbf169d37b/Formula/qemu.rb). The results are summarized in the table below:

|`images.location`|default qemu|patched qemu|
|-|-|-|
|[impish/20220309](https://cloud-images.ubuntu.com/impish/20220309/)\*1|:x:|:white_check_mark:|
|[impish/20220204](https://cloud-images.ubuntu.com/impish/20220204/)|:white_check_mark:|:white_check_mark:|
|[impish/20220201](https://cloud-images.ubuntu.com/impish/20220201/)|:white_check_mark:|:white_check_mark:|
|[focal/20220308](https://cloud-images.ubuntu.com/focal/20220308/)|:x:|:white_check_mark:|
|[focal/20220307](https://cloud-images.ubuntu.com/focal/20220307/)|:white_check_mark:|:white_check_mark:|
|[focal/20220302](https://cloud-images.ubuntu.com/focal/20220302/)|:white_check_mark:|:white_check_mark:|

This patch seems to be working fine.

<details><summary>verbose logs</summary>

\*1:
shasum 7895f695a5e9d49ce13aa926a05d3043cea3063d https://cloud-images.ubuntu.com/impish/20220309/impish-server-cloudimg-arm64.img
shasum 7895f695a5e9d49ce13aa926a05d3043cea3063d https://cloud-images.ubuntu.com/releases/21.10/release-20220309/ubuntu-21.10-server-cloudimg-arm64.img

$ brew info qemu
qemu: stable 6.2.0 (bottled), HEAD
Emulator for x86 and PowerPC
https://www.qemu.org/
/opt/homebrew/Cellar/qemu/6.2.0 (162 files, 555.3MB) *
  Poured from bottle on 2022-01-10 at 23:03:27
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/qemu.rb
License: GPL-2.0-only
==> Dependencies
Build: libtool ✔, meson ✘, ninja ✘, pkg-config ✔
Required: glib ✔, gnutls ✔, jpeg ✔, libpng ✔, libslirp ✔, libssh ✔, libusb ✔, lzo ✔, ncurses ✔, nettle ✔, pixman ✔, snappy ✔, vde ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 31,778 (30 days), 119,643 (90 days), 292,728 (365 days)
install-on-request: 17,891 (30 days), 67,213 (90 days), 206,631 (365 days)
build-error: 24 (30 days)

$ qemu-system-aarch64 --version
QEMU emulator version 6.2.0
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers

----------------------

$ brew uninstall --ignore-dependencies qemu
$ curl -O https://raw.githubusercontent.com/AkihiroSuda/homebrew-core/177d583c741f4f50a12f326f632c54dbf169d37b/Formula/qemu.rb
$ brew install --build-from-source ./qemu.rb

$ brew info qemu
qemu: stable 6.2.0 (bottled), HEAD
Emulator for x86 and PowerPC
https://www.qemu.org/
/opt/homebrew/Cellar/qemu/6.2.0_1 (162 files, 554.7MB) *
  Built from source on 2022-03-12 at 15:08:43
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/qemu.rb
License: GPL-2.0-only
==> Dependencies
Build: libtool ✔, meson ✔, ninja ✔, pkg-config ✔
Required: glib ✔, gnutls ✔, jpeg ✔, libpng ✔, libslirp ✔, libssh ✔, libusb ✔, lzo ✔, ncurses ✔, nettle ✔, pixman ✔, snappy ✔, vde ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 31,778 (30 days), 119,643 (90 days), 292,728 (365 days)
install-on-request: 17,891 (30 days), 67,213 (90 days), 206,631 (365 days)
build-error: 24 (30 days)

$ qemu-system-aarch64 --version
QEMU emulator version 6.2.0
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers

----------------------

$ limactl start ./docker-impish-20220309.yaml
$ limactl shell docker-impish-20220309 uname -a
Linux lima-docker-impish-20220309 5.13.0-35-generic #40-Ubuntu SMP Mon Mar 7 08:06:10 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

</details>

**Comment by AkihiroSuda** [comment] 2022-03-12 07:01
Thank you @fuzmish , opened PR https://github.com/Homebrew/homebrew-core/pull/96743

**Comment by AkihiroSuda** [comment] 2022-03-14 08:02
## Update (Mar 14, 2022)

:warning: Running recent Linux guests on M1 macOS needs Homebrew's QEMU 6.2.0_1 or later.
**Run `brew upgrade` to upgrade QEMU.**
Intel macOS users are NOT affected by this issue.
For the further information, see https://github.com/lima-vm/lima/pull/734 and https://github.com/Homebrew/homebrew-core/pull/96743 .

**Closed by AkihiroSuda** 2022-03-14 08:02 UTC
Labels: priority/high, platform/ARM, guest/ubuntu, component/qemu
