### ISSUE TITLE
Allow setting of destination for mounts

### ISSUE THREAD

**Issue by pauldthomson** [lima-vm/lima#659] opened 2022-02-17 05:28 UTC
As seen here, the mounts `location` is used as both the source and destination: https://github.com/lima-vm/lima/blob/ae9733c7f1d27c59334663dbe481f02141f15319/pkg/hostagent/mount.go#L55-L58

I want to be able to mount my `~/.aws/credentials` in order to use the [Amazon ECR Credential Helper](https://github.com/awslabs/amazon-ecr-credential-helper), however as `~` on my mac expands to `/Users/myusername`, the `.aws` folder is mounted there, but `$HOME` inside the VM is `/home/myusername.linux`, so the cred helper doesn't find the creds.

There's probably other ways to work around this, but would being able to set the destination for a mount be desirable?

**Comment by jandubois** [comment] 2022-02-17 06:09
This is mostly a duplicate of #130 (so yes, I agree that being able set a different mount point is desirable).

As for the credentials helper, doesn't this solve the issue for you:

```console
$ lima ln -s /Users/myusername/.aws /home/myusername.linux/.aws
```

**Comment by pauldthomson** [comment] 2022-02-17 06:20
Yeah, creating a link is what I've done, but thought there might be other use cases for being able to configure the destination, e.g. reusable/shareable configs

**Closed** 2022-05-27 06:12 UTC
Labels: enhancement
