### ISSUE TITLE
Support specifying mount location within guest

### ISSUE THREAD

**Issue by chancez** [lima-vm/lima#866] opened 2022-05-23 19:26 UTC
### Description

From what I can tell, you cannot choose where you what a mount to be mounted at within the VM, you can only configure the source path, not the destination:
https://github.com/lima-vm/lima/blob/001d8d0ef6f4d1a0a1551b975dbd437684e0f4d7/pkg/limayaml/limayaml.go#L65-L70

I'd like to be able to specify the mount path, so I can share certain files into my Lima user's $HOME. 

Eg: Mounting my `~/.kube/config` to `/home/chancezibolski.linux/.kube/config` (since my Lima user's $HOME != my Mac $HOME).

**Comment by jandubois** [comment] 2022-05-23 20:03
See also #130 and #659

**Comment by chancez** [comment] 2022-05-23 20:32
Ugh I tried to look for existing issues but apparently failed. Thanks.

**Comment by AkihiroSuda** [comment] 2022-05-23 20:37
Duplicate of #659

**Closed by AkihiroSuda** 2022-05-23 20:37 UTC
Labels: duplicate, enhancement
