### ISSUE TITLE
`limactl inspect --format json` and `limactl ls --format json` produces the exactly same output

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#1282] opened 2023-01-06 00:36 UTC
>  Noticed that `limactl inspect --format json` and `limactl ls --format json` produces the exactly same output now.
>
> Probably, `limactl ls` isn't expected to print the config field?

_Originally posted by @AkihiroSuda in https://github.com/lima-vm/lima/issues/1249#issuecomment-1372978716_

**Comment by AkihiroSuda** [comment] 2023-01-09 01:07
What should we do?  @deitch cc @jandubois @afbjorklund 

Do we want to remove the config field from the `limactl ls --format json`, or just remove the `limactl inspect` command?
(The `limactl inspect` command is only present in the master branch, so removing it is not a breaking change)

**Comment by jandubois** [comment] 2023-01-09 06:26
> Do we want to remove the config field from the `limactl ls --format json`, or just remove the `limactl inspect` command?

I have a hard time making up my mind:

* I was taken aback by the addition of the `config` field in the `ls` json output because it is no longer easily browsable.

* On the other hand, it seems silly to have an additional command that is essentially just a subset of an existing command, but with the added `config` field.

I think I would prefer to drop the `inspect` command and leave the `config` field in the `ls` command.

We could require a `--config` or `--inspect` option on the `ls` command to add the `config` field, to retain the existing short list, and have the `config` only added on demand. But I'm not sure there is a good reason for this; the json and yaml output is really meant for machine consumption, and additional fields are just ignored by consumers that don't want/need them.

**Comment by jandubois** [comment] 2023-01-09 06:42
> We could require a `--config` or `--inspect` option on the `ls` command to add the `config` field

On further reflection, I think this is not a good idea, and we should just always include `config`.

I do wonder if we need further documentation in `limactl ls --list-fields` to document the substructure of the `.Config` field. Or maybe we leave this as "under-documented" and let people go looking in the source code, if they want to use `config` data in their format strings:

```console
$ limactl ls -f '{{.Name}} - {{.Config.MountType}}' docker podman
docker - reverse-sshfs
podman - reverse-sshfs

$ limactl ls -f '{{.Config.Message}}' docker
To run `docker` on the host (assumes docker-cli is installed), run the following commands:
------
docker context create lima-{{.Name}} --docker "host=unix://{{.Dir}}/sock/docker.sock"
docker context use lima-{{.Name}}
docker run hello-world
------
```

**Comment by afbjorklund** [comment] 2023-01-09 15:59
I didn't like having `defaultTemplate` in `limactl info`, and I don't like `config`in `limactl ls`.

I think it clutters the output ? But I know that you can remove it, with a degree in jq-ology...

`limactl info | jq 'del (.defaultTemplate)'`

`limactl ls --json | jq 'del (.[].config)'`

But having it in the JSON is not so bad, since I guess that is not meant for human consumption ?

I would prefer to not see in the default output, unless it is requested using something like `inspect`

**Comment by jandubois** [comment] 2023-01-09 17:22
> I didn't like having `defaultTemplate` in `limactl info`, and I don't like `config`in `limactl ls`.

Same here,

> But having it in the JSON is not so bad, since I guess that is not meant for human consumption ?

This ⬆️ 
 
> I would prefer to not see in the default output, unless it is requested using something like `inspect`

I thought so too at first, but does it make things easier for the majority of users? Why do they need to learn to add additional options to get the full set of data; shouldn't that be the default.

And for those weirdos like us, who like looking at raw JSON output, we know how to filter things with `jq`.

So I think optimizing for the less-knowledgeable user makes sense, and I've reverted my opinion to now want to include `config` all the time.

**Comment by AkihiroSuda** [comment] 2023-01-11 06:06
> I think I would prefer to drop the inspect command and leave the config field in the ls command.
>
> we should just always include config.

SGTM

@deitch WDYT?

**Comment by deitch** [comment] 2023-01-11 08:10
Agreed. The original inspect command was intended to get the config, but it made sense to include the information as well, since it is "inspect VM", not the subset "inspect config of VM", which, in turn, was easier by shared code.

I think that as long as the table listing of `limactl ls` produces the simple table output (which it does), then having `limactl ls` in json mode include everything else is fine, and we either can get rid of `inspect`, or just make it an alias for `list`.

**Comment by afbjorklund** [comment] 2023-01-11 21:20
It was _simpler_ before, when they all showed the same information - but in different formats.

Now when things are auto-hidden in table, it is a bit harder to understand what is going on...

But I mostly use the `--json` output to communicate with the GUI, and it can drop the extra fields.
To show the template/example, then it uses the editor on the `lima.yaml` (not the merged results).

Also because the [ Inspect ] button doesn't match the new `inspect` command, but shows guest info.
It probably should either be renamed to something else, or show the merged template as well ?

----

```yaml
{
  "name": "default",
  "status": "Running",
  "dir": "/home/anders/.lima/default",
  "vmType": "qemu",
  "arch": "x86_64",
  "cpuType": "host",
  "cpus": 4,
  "memory": 4294967296,
  "disk": 107374182400,
  "sshLocalPort": 60022,
  "hostAgentPID": 703840,
  "driverPID": 703866
}
```

![lima-gui-inspect-default](https://user-images.githubusercontent.com/10364051/211920133-860c6d40-066c-4f04-87b0-21df24d54044.png)

**Comment by AkihiroSuda** [comment] 2023-01-12 04:22
PR
- https://github.com/lima-vm/lima/pull/1295

**Closed** 2023-01-14 02:26 UTC
Labels: bug, priority/high, area/cli

**Comment by afbjorklund** [comment] 2023-01-14 10:13
> or just remove the limactl inspect command?

Ironically, I had forgotten about the `limactl config`

* https://github.com/lima-vm/lima/issues/443

So now we don't have those simple commands, but instead we can do whatever we want with enough JSON-ology ?

Doing a similar change for `limactl message`, which now turned into documenting the API of a new template engine.
